### PR TITLE
js-arrays-iterators-PREVIOUS

### PR DESCRIPTION
**Pull request by tgaff**
fun with merging 

This is only the sources from previous cohorts -- I'll use a separate PR for 27-28.

### CODE REVIEW

**Comment by tgaff** [comment]
I'm not seeing a 22-23 iterator module.  @bgveenstra @jlopker Am I missing something?

**Comment by nathanallen** [comment]
holy moly, how are you doing that?

**Comment by tgaff** [comment]
Is that bad?  I applied 24's using a patch and 25's using filter-branch with the subdirectory-filter.

**Comment by nathanallen** [comment]
This is fantastic. I didn't know patch carried over commit history, I though it was more like a `cherry-pick`.

**Comment by tgaff** [comment]
So for 24 I did something like:

```
git log --pretty=email --patch-with-stat --reverse --full-index --binary -- some/directory/or/other > ../patch.txt
```

then imported the patches (which strangely were self-conflicted and turned out to be a pain)

```
git am --ignore-whitespace < ../patch.txt
```

For 25 it was more complicated but ultimately quicker.

```
git filter-branch -f --subdirectory-filter some/directory/or/other  --  --all -f
```

then merge it in (you'll need both as remotes)

**Comment by tgaff** [comment]
http://thread.gmane.org/gmane.comp.version-control.git/5126/

**Comment by tgaff** [comment]
I don't think this needs much review.  I didn't change anything from the upstreams (parallel streams?) outside of resolving a patch-merge issue.

-- assuming I didn't screw-up the git stuff

**Pull request merged**
