### PR TITLE
27-28_w02-d01-dawn-js-array-iterators

### PR DESCRIPTION
**Pull request by tgaff**
[Completes #45]

### CODE REVIEW

**Comment by tgaff** [comment]
@nathanallen Would you rather do [challenge_b](https://github.com/SF-WDI-LABS/shared_modules/blob/js-arrays-iterators/01-front-end-basics/js-array-iterators/25/exercises_b.md) or the [lab with tests](https://github.com/sf-wdi-25/building_iterators).

There's definitely NOT time for both.  In 25 we didn't get anywhere near completing all of that.  I'm leaning towards the one with tests.  I found that the wording in exercises_b rather confused students.  We'd need to add a bunch of examples in there.  

Another alternative might be to do a part of exercises_b as a "I-do/we-do" and still try to get to the lab too.  But keep in mind I'm also planning to do (at least in my lesson-plan) a "you-do then we-do" mini-exercise with each part of (exercises_a)[https://github.com/SF-WDI-LABS/shared_modules/blob/js-arrays-iterators-27-28/01-front-end-basics/js-array-iterators/27-28/exercises_a.md] so I doubt they'll get more than a few minutes to start the lab.

**Comment by tgaff** [comment]
@nathanallen

**Comment by nathanallen** [comment]
@tgaff  GTM if you're happy with it.

**Comment by nathanallen** [comment]
@tgaff Merged in only your initial changes (See https://github.com/SF-WDI-LABS/shared_modules/pull/55). We can hold off on this branch.

**Pull request closed without merging**
